### ISSUE TITLE
IndexError: Layer [Dot11] not found

### ISSUE THREAD

**Issue by alloygoh** [ICSec/pyDot11#26]
Hi, i cant seem to encrypt the packets captured in wireshark and saved as a pcap.
It gives me a index error.

``` python pyDot11 -f test.pcap -p mypassword -b mybssid -t wep ``` was the command used.
Full error message below
``` Traceback (most recent call last):
  File "pyDot11", line 256, in <module>
    main(args)
  File "pyDot11", line 215, in main
    packetParser(pkt)
  File "pyDot11", line 87, in engine
    if pktFilter(packet):
  File "pyDot11", line 75, in pktFilter
    if packet[Dot11].type == 2 and\
  File "/root/Desktop/ctf_create/pyDot11/scapy/packet.py", line 966, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [Dot11] not found
```

**Comment by alloygoh** [comment]
I have removed the password and bssid for security sakes

**Comment by stryngs** [comment]
Hi @alloygoh 
I need to understand a little bit more what it is you are trying to do.  If I understand correctly, you want to parse test.pcap using pyDot11? i.e.:

./pyDot11 -f open_pings.pcap -p 'password' -b 'monkies' -t wep
pyDot11 up and running on tap0
Press Enter to Iterate through open_pings.pcap

^^ That's what you typically should see; but as you're seeing a layer not found issue; I'd have to see at least that specific frame to understand what the issue is.  I suspect it's something to do with the [Dot11] layer not being found, but without the file to test, only a guess.

As well, what is your end goal here?  Sometimes ./pyDot11 is the way to go, and sometimes from pyDot11 import * is a better choice.

Thoughts?

**Comment by alloygoh** [comment]
I do see the pyDot11 up and running on tap0
Press Enter to Iterate through open_pings.pcap

My end goal is to try and encrypt the packets to try and create a CTF challenge for my friends to crack the wep authentication.

**Comment by stryngs** [comment]
Hi @alloygoh 
So you could do that by using the module itself.  The wrapper script (pyDot11) is just that, useful wrappers.  To get the full power of pyDot11, you have to use it as a module.

Check it out:
## Example of taking a packet from Open Wifi, and then encrypting it:
from pyDot11 import *
from scapy.utils import rdpcap
openPkts = rdpcap('PCAPs/ICMPs/open_pings.pcap')
openPkts[1].summary()
input = openPkts[1].__class__(str(openPkts[1])[0:-4])
encPkt = wepEncrypt(input, '0123456789')
encPkt.summary()

**Comment by alloygoh** [comment]
I will give it a try. Thank you so much

**Comment by stryngs** [comment]
@alloygoh Please let us know how it works.  Thanks.

**Comment by alloygoh** [comment]
hi, when encrypting using the module itself, i get the error of 
```Traceback (most recent call last):
  File "./testing.py", line 10, in <module>
    encPkt = wepEncrypt(input, '0123456789')
  File "/usr/local/lib/python2.7/dist-packages/pyDot11/__init__.py", line 34, in wepEncrypt
    stream = wepCrypto.encoder(pkt, iVal, keyText)
  File "/usr/local/lib/python2.7/dist-packages/pyDot11/lib/wep.py", line 88, in encoder
    wepICV = self.pt.endSwap(hex(crc32(str(pkt[LLC])) & 0xffffffff))
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 966, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [LLC] not found
```
My code is as such
```
#!/usr/bin/env python2

from pyDot11 import *
from scapy.utils import rdpcap
openPkts = rdpcap('test.pcap')
openPkts[1].summary()


input = openPkts[1].__class__(str(openPkts[1])[0:-4])
encPkt = wepEncrypt(input, '0123456789')
encPkt.summary()
```

**Comment by stryngs** [comment]
@alloygoh 

I've just pushed some synchronization updates; after you see my update, let's make sure we're on the same page:

Install the newest version of packetEssentials.  For this you can pull from the main repo for it or grab it from RESOURCEs.

After the packetEssentials update, then upgrade pyDot11.

Here are my test results.  For this test, dBug.py represents your pasted code, but instead of test.pcap which I do not have, I used the open_pings.pcap.  As you can see in the output, my tests were successful.  As mine were good, please verify that open_pings.pcap processes properly on your end.  If that succeeds, then there would be an issue with your pcap.  It could be a myriad of things if that is the case.  Either way, let me know.  Cheers



In [2]: with open('dBug.py', 'r') as iFile:
   ...:     p = iFile.read().splitlines()
   ...:     

In [3]: p
Out[3]: 
['#!/usr/bin/env python2',
 '',
 'from pyDot11 import *',
 'from scapy.utils import rdpcap',
 "openPkts = rdpcap('open_pings.pcap')",
 'openPkts[1].summary()',
 '',
 '',
 'input = openPkts[1].__class__(str(openPkts[1])[0:-4])',
 "encPkt = wepEncrypt(input, '0123456789')",
 'encPkt.summary()',
 '']

In [4]: %run dBug.py

In [5]: encPkt
Out[6]: <RadioTap  version=0 pad=0 len=38 present=TSFT+Flags+Rate+Channel+dBm_AntSignal+b14+b29+Ext notdecoded=' \x08\x00\xa0 \x08\x00\x00t\x8fr#\x00\x00\x00\x00\x10ll\t\xc0\x00\xdc\x00\x00\x00\xd4\x00\xdb\x01' |<Dot11  subtype=8 type=Data proto=0 FCfield=from-DS+wep ID=11264 addr1=c4:d9:87:e4:62:5e addr2=ce:e1:d5:00:13:9a addr3=4e:40:cd:16:5a:1d SC=21536 |<Dot11QoS  Reserved=0 Ack_Policy=0 EOSP=0 TID=0 TXOP=0 |<Dot11WEP  iv='\xba0\x0e' keyid=0 wepdata='\xae8\xd5\x03\x8b\xad\x92m\x9b\xeb{i2\x95\xbb\xaa\xca.\x88\xb3\xfe\x8c\xdc\xd4\xc8\xbb\x80&`Bq\xb4\xab"\x98\x9a\x8ee\x9f\xaf\xfa\xdb\xe6&B\xfc\xae=\xc9O\x8a`@\xd6\xec\xfe\xb9w"\x18\x14\xee\xa0\x0e\xba\xf9?\xd3\xb0\xea\x89HTL\x0b\xc5(\xc1\x9c\xc7\x9a\xf9\x7f\\1\xc5\xd2\x82\xdf\x8d\xd7\xcfD\x9d+5' icv=3170771257 |>>>>

**Comment by alloygoh** [comment]
Hi, i am unable to replicate your output. How did you execute ur program?

**Comment by stryngs** [comment]
Hi @alloygoh 
So the output you saw comes from ipython.  To launch, simply cd to the directory where your script is, and then type:
ipython

From there you're in an interactive Python IDE (much better than, IDLE)

The %run command is what launched your program.  Give it a whirl

**Comment by alloygoh** [comment]
@stryngs I have revised my question alr

**Comment by stryngs** [comment]
@alloygoh so it would seem it is the pcap.  When you saved it in wireshark, which format did you use?  There is a -ng type version, don't use that, use the regular .pcap per se.  If you need to convert, simply open with wireshark, then save as.

Lemme know.

**Comment by alloygoh** [comment]
I saved it as a pcap. Not a pcap-ng

**Comment by stryngs** [comment]
@alloygoh  Are you able to share the pcap?

**Comment by alloygoh** [comment]
It is just a normal capture from my wifi card. Nothing special

**Comment by alloygoh** [comment]
It's fine. I decided to drop the idea. Thank you so much!
