### ISSUE TITLE
ccmp decoder error

### ISSUE THREAD

**Issue by birdg0** [ICSec/pyDot11#28]
The code of ccmp decoder
```
PN[2] = pload[4]
PN[3] = pload[5]
```
should be
```
PN[2] = pload[5]
PN[3] = pload[4]
```

**Comment by stryngs** [comment]
Hi @birdg0 

I grepped out the pload stuff a bit:

./SRC/pyDot11/lib/ccmp.py:113:        PN[0] = pload[7]
./SRC/pyDot11/lib/ccmp.py:114:        PN[1] = pload[6]
./SRC/pyDot11/lib/ccmp.py:115:        PN[2] = pload[4]
./SRC/pyDot11/lib/ccmp.py:116:        PN[3] = pload[5]
./SRC/pyDot11/lib/ccmp.py:117:        PN[4] = pload[1]
./SRC/pyDot11/lib/ccmp.py:118:        PN[5] = pload[0]

It has been so unbelievably long since I touched ccmp.py.  That was a summer spent in the IEEE docs.  Would most likely takes me weeks to get back up to speed.

I'm not sure why the decision to make 4 and 5 be flipped like that was chosen.  What's odd, if that really is the case, then how does pyDot11 currently successfully decrypt WPA.  I can try and make sometime to do some test case comparisons, to see what happens when we flip the bits like you suggested.

I know we aren't able to decrypt everything, but I'd always figured it due to the entropy of just how fast the wifi goes back and forth; not a formula problem.

Would you do me a big favor and reference out where you determined we had the code incorrect?  That would go a long way in ensuring a nice audit of ccmp.py.

Thank you!

**Comment by birdg0** [comment]
I just saw the code of encryptCCMP shown below
```
ccmphdr = bytearray([PN[5], PN[4], 0x00, 0x20, PN[3], PN[2], PN[1], PN[0]])
```
So the code of ccmp decoder should be
```
PN[0] = pload[7]
PN[1] = pload[6]
PN[2] = pload[5]
PN[3] = pload[4]
PN[4] = pload[1]
PN[5] = pload[0]
```
You can test it by using decoder to decrypt the ciphertext returned by encryptCCMP.

**Comment by stryngs** [comment]
@birdg0 Sorry if it will take me a while to reply.  Little bit too much going on IRL to deal with github right now.  If you would, make a fork, show me what you're talking about.  I have no idea what happens if you change those indexes.  Just haven't had the freetime for 802.11 I wish I did.  I'm very curious of your success ratios.  I would think you'd only get what I didn't catch, the why would be interesting, etc..  What would be interesting is if we had successes that were the same.

If you would, shoot me an email, info@ethicalreporting.org?

**Comment by stryngs** [comment]
Closing this issue out.  If wanted follow up with a PR on https://github.com/stryngs/pyDot11.
