### ISSUE TITLE
Trouble Decrypting with DS Network

### ISSUE THREAD

**Issue by william-r-dieter** [ICSec/pyDot11#9]
I am having trouble getting decryption to work for WPA2-PSK for my home network.  The code that is decrypting works for another network.  The most obvious difference between the two networks is that the network that works has an AP/Router in a single unit (SA == TA for fromDS, RA == DA for toDS), and the network that does not has a separate AP and Router connected by Ethernet (SA == Router, TA == AP for fromDS, RA == AP, DA == Router for toDS).

I have only tried the two networks, so the problem could be somewhere else.  Have you tried pyDot11 with the BSSID not always matching either the SA or DA?

[ds-demo-short2.pcap.gz](https://github.com/ICSec/pyDot11/files/1251012/ds-demo-short2.pcap.gz) is my input file.  It is encrypted with WPA2-PSK.  I created a guest network for this bug report with SSID of `ds-demo` and PSK of `pydot11!`.  You can filter down to just the client STA of interest in wireshark with a filter of `wlan.addr == ac:cf:85:ca:e6:d2`.

After decrypting, I get [ds-demo-short2-bug.pcap.gz](https://github.com/ICSec/pyDot11/files/1251014/ds-demo-short2-bug.pcap.gz).  You can see the EAPOL handshake end in Packet 18.  The first QoS Data packet is Packet 28.  When decryption works, the LLC.DSAP and LLC.SSAP are pretty much always 0xaa, but in this case they are a lot of different random values.

**Comment by william-r-dieter** [comment]
I have a few more clues, but still not sure what is going on.  In another packet trace taken from a different network, there are a few Dot11QoS data frames with non-zero TID in the QoS Control field.  These frames are not decrypting properly.   I can't share that trace it due to other things in the trace, but maybe could generate a clean one if there is desire.  I also noticed that my home network is almost always setting a non-zero QoS Control field, either because the TID is non-zero or because the A-MSDU bit is set.

I am not sure why the TID, or any other field in the QoS Control, would make a difference with decryption.  QoS Control is supposed to be part of the AAD for CCMP, and I don't see it getting added.  However, for the purpose of decryption, QoS Control appears to be used only in the MIC computation, and as far as I can tell, from the code and the spec, MIC should only affect whether the frame is considered valid, not change the actual decrypted contents.  Also, I don't see any place where a frame would get flagged or rejected because of a bad MIC, so I don't think the frames are being silently thrown away.

**Comment by stryngs** [comment]
So, at a glance it seems I am not crazy, there in fact could be something which I had seen in the past, but couldn't repeat it, so wrote it off as a maybe.  The maybe just might be coming home to roost; of which I'm grateful, even though it presents it's own set of issues

I ran it in wireshark and decrypted it as wpa-pwd using pydot11!:ds-demo; and wireshark failed to decrypt it.  I then verified with aircrack-ng and agree the ESSID and PSK is what you say it is, why Wireshark is being difficult I don't know, thus I have to make some guesses here.

Using the new found capabilities of pyDot11 to read from a file, I ran it.  pyDot11 does what it does, but nothing is issued to tap0, thus your issue here....

Going old-skool, I then ran my trusty friend airdecap-ng, same issue:
airdecap-ng -p 'pydot11!' ds-demo-short2.pcap -e 'ds-demo'
Total number of packets read           721
Total number of WEP data packets        26
Total number of WPA data packets       249
Number of plaintext data packets         0
Number of decrypted WEP  packets         0
Number of corrupted WEP  packets         0
Number of decrypted WPA  packets         0

... Nothing is decrypting, not even with tools better written than my own....  I'm going to reach out to Mister_X, but I'm pretty sure I had the syntax proper...

Continuing, I dove into manual mode:
from scapy.all import *
p = rdpcap('ds-demo-short2.pcap')
p[707]
## Yields
addr1=f2:9f:c2:32:15:fa
addr2=d0:7e:35:d3:e8:5c
addr3=00:22:3f:23:a5:c8

!  This is a big issue.  As this is a QOS I "assume" this is a Data Packet on the network in question.  As the frame in question is a TO-DS, it should be BSD, as in BSSID, SOURCE, DESTINATION.
So, for p[707], is this a frame sent to an Access Point, or is it sent to a client on the LAN?  If it is the former, then I know the issue and how to proceed.

Thoughts?

**Comment by william-r-dieter** [comment]
Sorry, I've been pulled off on another project for a bit and not had a lot of free time at home.  I am hoping to have a bit more time to look at it soon.

**Comment by stryngs** [comment]
Look forward to it @william-r-dieter =)  Some of the changes you requested have been put in.  The others we shall deal with when you are ready.  Cheers!

**Comment by stryngs** [comment]
@william-r-dieter you still around?

**Comment by william-r-dieter** [comment]
Hi @stryngs, I am doing a different job at work, so no longer working on the project I was using pyDot11 for, and also do not have access to the equipment to gather more data...

**Comment by stryngs** [comment]
Closing this issue out.  If wanted follow up with a PR on https://github.com/stryngs/pyDot11.
